<a href="https://colab.research.google.com/github/TaniaZharova2205/HSE/blob/main/Seminar_3_base.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Рекурсия

In [ ]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)
print(factorial(5))

120


In [ ]:
n! = (n - 1)! * n

In [ ]:
print(factorial(3))

6


In [ ]:
print(factorial(6150))

RecursionError: maximum recursion depth exceeded in comparison

In [ ]:
import sys

In [ ]:
sys.getrecursionlimit()

1200

In [ ]:
sys.setrecursionlimit(1300)

In [ ]:
sys.getrecursionlimit()

1300

**Задача 1**

Напишите рекурсивную функцию возведения в степень. Функция должна принимать на вход числа a, n и возвращать $a^n$.

In [ ]:
def power(a, n):
  if n < 0:
    return 1 / power(a, -n)
  if n == 0:
    return 1
  elif n % 2 == 0:
    return power(a, n // 2)**2
  else:
    return a * power(a, n - 1)


In [ ]:
power(2, -2)

0.25

### Работа с файлами

In [ ]:
with open('text_file_2.txt', 'w') as outfile:
    print('Файл, который нужно прочитать', file=outfile)


## считать .txt
Существуют разные способы открыть файл. Мы воспользуемся тем, который сам же и закроет файл. Это удобно, так как если забыть закрыть файл, можно потерять данные — особенно при записи. Конструкция `with open() as` открывает файл, позволяет взять из него все, что нужно, и закрывает файл.

В `open()` передаем название файла (который лежит в той же папке, что и код), а после `as` пишем псевдоним, с помощью которого будем обращаться к файлу внутри программы.

In [ ]:
with open('text_file_2.txt') as infile: # Открываем файл: пишем название файла и выбираем ему псевдоним
    print(infile)                     # Пробуем распечатать считанный файл

FileNotFoundError: [Errno 2] No such file or directory: 'text_file_4.txt'

In [ ]:
text = ''
with open('text_file_2.txt', mode='r', encoding = 'UTF-8') as file:
    for line in file:
        text += line

In [ ]:
text

'Файл, который нужно прочитать\n'

In [ ]:
file = open('text_file_2.txt', mode='r', encoding = 'UTF-8')

In [ ]:
for line in file:
  print(line)

In [ ]:
next(file) # file - это итератор

'Файл, который нужно прочитать\n'

In [ ]:
file.close()

In [ ]:
with open('text_file_2.txt', encoding='UTF-8') as infile:
    text = infile.read() #считать все строки

In [ ]:
text

'Файл, который нужно прочитать\n'

In [ ]:
with open('text_file_2.txt', encoding='UTF-8') as infile:
    lines = infile.readlines() #считать все строки в список

In [ ]:
lines

['Файл, который нужно прочитать\n']

### Запись в файл

In [ ]:
important_text = 'Очень важный текст.\n В нем даже несколько строк'
with open('text_file_2.txt', 'w') as outfile:
    print(important_text, file=outfile)

In [ ]:
important_text_2 = 'Это другой важный текст.'
with open('text_file_2.txt', 'w') as outfile:
    print(important_text_2, file=outfile)

In [ ]:
important_text_3 = 'А это совсем важный текст. Очень!'
with open('text_file_2.txt', 'a') as outfile:
    print(important_text_3, file=outfile)

Библиотека NumPy (Numeric Python)  —  быстрая библиотека для математики в Python. Основная структура данных  —  массив `numpy.array` для хранения данных одного типа

##### Создание массива

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([0.01, 2, 4, 0.1, -2, 0, 1, -2])

print(a)
print(b)
print(b[1])
print(b[1:7:2])

[1 2 3 4 5]
[ 0.01  2.    4.    0.1  -2.    0.    1.   -2.  ]
2.0
[2.  0.1 0. ]


In [ ]:
c = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 20, 30, -10, 0]]) # многомерный массив
print(c)
print(c.shape, c.dtype)
print( c[1][2])

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 10  20  30 -10   0]]
(3, 5) int64
8


In [ ]:
lst = [1, 2, ['a', 'b']]

In [ ]:
c = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 20, 30, -10, 0]])

In [ ]:
c[0][1] = 200

In [ ]:
c

array([[  1, 200,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 10,  20,  30, -10,   0]])

In [ ]:
c.dtype

dtype('int64')

In [ ]:
c[0][1] = 10e18

OverflowError: Python int too large to convert to C long

In [ ]:
10e18

1e+19

In [ ]:
d = np.arange(2, 19, 3)
print(d)

[ 2  5  8 11 14 17]


In [ ]:
print(np.random.rand(2, 2)) # массив из чисел их равномерного распределения [0, 1]

[[0.08161091 0.22937057]
 [0.91279608 0.31438411]]


In [ ]:
random_array = np.random.randn(2, 3, 2)
random_array


array([[[-0.19381594, -2.41563388],
        [-0.55897646,  1.9902527 ],
        [-1.21411849, -3.52241983]],

       [[-1.15778943,  1.08671425],
        [ 0.64978869,  2.12976327],
        [-1.22506511, -0.33294731]]])

In [ ]:
random_array.shape

(2, 3, 2)

Используются типы данных Си: `int8`, `int32`, `int64`...

In [ ]:
c[1][2] = 80

In [ ]:
c

array([[  1,   2,   3,   4,   5],
       [  6,   7,  80,   9,  10],
       [ 10,  20,  30, -10,   0]])

In [ ]:
c[1][2] = 80

In [ ]:
c.dtype

dtype('int64')

In [ ]:
c[1][2] = 10e18 #переполнение

OverflowError: Python int too large to convert to C long

In [ ]:
10e18

1e+19

In [ ]:
I = np.eye(10, 10)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
array = np.array([0, 1, 2, 3, 4, 5])
print(array.dtype)
array

int64


array([0, 1, 2, 3, 4, 5])

In [ ]:
array = np.array([0, 1, 2, 3, 4, 5], dtype='int16')
print(array.dtype)
array

int16


array([0, 1, 2, 3, 4, 5], dtype=int16)

In [ ]:
array[1] =array[1] * 10

In [ ]:
array[1] = 'abc'

ValueError: invalid literal for int() with base 10: 'abc'

In [ ]:
array = np.array([0, 1, 'abc'])
print(array.dtype)
array

<U21


array(['0', '1', 'abc'], dtype='<U21')

In [ ]:
a = np.zeros(10)
print(a)

a = np.zeros((3, 2))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


Многомерные массивы:

In [ ]:
array = np.array([[[1, 10, 3], [2, 12], [3, 30]], [[4, 40], [5, 50], [6, 60]], [[7, 70], [8, 80], [9, 90]]], dtype='object')

In [ ]:
array

array([[list([1, 10, 3]), list([2, 12]), list([3, 30])],
       [list([4, 40]), list([5, 50]), list([6, 60])],
       [list([7, 70]), list([8, 80]), list([9, 90])]], dtype=object)

In [ ]:
array.shape

(3, 3)

In [ ]:
print(array.dtype, array.shape, array.ndim, array.size)

int64 (3, 3, 2) 3 18


In [ ]:
c

array([[  1, 200,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 10,  20,  30, -10,   0]])

In [ ]:
c.flatten()

array([  1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  10,  20,  30,
       -10,   0])

In [ ]:
c.shape

(3, 5)

In [ ]:
c.reshape(5, 3)

array([[  1, 200,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  10,  20],
       [ 30, -10,   0]])

In [ ]:
array.reshape(2, 9)

ValueError: cannot reshape array of size 9 into shape (2,9)

In [ ]:
array = np.array([[1, 2], [1, 2, 3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
array = np.array([[1, 2], [1, 2, 3]], dtype="object")

In [ ]:
array

array([list([1, 2]), list([1, 2, 3])], dtype=object)

С numpy-массивами может быть удобно работать, потому что все действия в них выполняются поэлементно:

In [ ]:
lst1 = [0, 1, 2, 3, 4, 5]
lst2 = [3, 1, 28, 3, 2, 8]
print(lst1 + lst2)

[0, 1, 2, 3, 4, 5, 3, 1, 28, 3, 2, 8]


In [ ]:
array1 = np.array([0, 1, 2, 3, 4, 5])
array2 = np.array([3, 1, 28, 3, 2, 8])
print(array1 + array2)

ValueError: operands could not be broadcast together with shapes (7,) (6,) 

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-2, 3, 8], [1, 9, 11]])
print(A, end = '\n\n')
print(B, end = '\n\n')
print(A + B, end = '\n\n')
print(A * B, end = '\n\n') # не умножение матриц, а поэлементное умножение!
print(np.dot(A, B)) # а вот это умножение матриц, которое упадет из-за несоответствия размерностей

[[1 2 3]
 [4 5 6]]

[[-2  3  8]
 [ 1  9 11]]

[[-1  5 11]
 [ 5 14 17]]

[[-2  6 24]
 [ 4 45 66]]



ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
C = np.array([[1, 2], [4, 5], [6, 7]])
print(B)
print(C)
print(np.dot(B, C))

[[-2  3  8]
 [ 1  9 11]]
[[1 2]
 [4 5]
 [6 7]]
[[ 58  67]
 [103 124]]


##### Арифметические операции

In [ ]:
lst1 = [1, 2, 3]
lst2 = [-1, -6, 30]
print(lst1 + lst2)

lst1_array = np.array([1, 2, 3])
lst2_array = np.array([-1, -6, 30])
print(lst1_array + lst2_array)

[1, 2, 3, -1, -6, 30]
[ 0 -4 33]


Если в операции участвуют два массива одинакового размера, операции считаются для соответствующих пар:

In [ ]:
print(lst2_array)
print(lst2_array * 6)
print(lst2_array * 2.8)
print(lst2_array + 2)
print(lst2_array - 20)
print(lst2_array**2)

[-1 -6 30]
[ -6 -36 180]
[ -2.8 -16.8  84. ]
[ 1 -4 32]
[-21 -26  10]
[  1  36 900]


In [ ]:
print(lst1_array)
print(lst2_array)
print()
print(lst1_array * lst2_array)
print(lst1_array - lst2_array)
print(lst1_array / lst2_array)
print(lst1_array // lst2_array)
print(lst1_array ** 2)

[1 2 3]
[-1 -6 30]

[ -1 -12  90]
[  2   8 -27]
[-1.         -0.33333333  0.1       ]
[-1 -1  0]
[1 4 9]


In [ ]:
np.unique([1, 2, 4, 2, 2, 1]) # уникальные значения

array([1, 2, 4])

In [ ]:
print(C.dtype, C.shape, C.ndim, C.size)

int64 (3, 2) 2 6


##### Индексация

In [ ]:
a = np.array([1, -2, 25, -4, -12])
print(a[a > 0])

[ 1 25]


In [ ]:
a = np.array([ 1,  2, 25, 10, -1])

In [ ]:
b = np.array([-2, -2,  3, 10, 15])

In [ ]:
print(a[(a > 0) | (b > 0)])

[ 1  2 25 10 -1]


In [ ]:
print(a[(a > 0) & (b > 0)])

[25 10]


In [ ]:
C = np.array([[-2, -2, 3, 10, 15], [2, -20, 3, 8, 15]])

In [ ]:
a = np.array([[[1, 2], [3, 4], [5, 6]]])

In [ ]:
a.shape

(1, 3, 2)

##### Математика

In [ ]:
a = np.array([1, 2, 25, 10, -1])
np.mean(a), np.min(a), np.max(a), np.sum(a), np.std(a)

(7.4, -1, 25, 37, 9.562426470305537)

In [ ]:
print(np.sin(2), np.exp(2))
print(np.sin(a), np.exp(a))

0.9092974268256817 7.38905609893065
[ 0.84147098  0.90929743 -0.13235175 -0.54402111 -0.84147098] [2.71828183e+00 7.38905610e+00 7.20048993e+10 2.20264658e+04
 3.67879441e-01]


In [ ]:
C = np.array([[-2, -2, 3, 10, 15], [2, -20, 3, 8, 15]])
C

array([[ -2,  -2,   3,  10,  15],
       [  2, -20,   3,   8,  15]])

In [ ]:
C.shape

(2, 5)

In [ ]:
np.min(C)

-20

In [ ]:
np.min(C, axis=0)

array([ -2, -20,   3,   8,  15])

In [ ]:
np.min(C, axis=1)

array([ -2, -20])

In [ ]:
np.mean(C)

3.2

In [ ]:
np.mean(C, axis=0)

array([  0., -11.,   3.,   9.,  15.])

In [ ]:
np.mean(C, axis=1)

array([4.8, 1.6])

In [ ]:
C

array([[ -2,  -2,   3,  10,  15],
       [  2, -20,   3,   8,  15]])

In [ ]:
C.dtype

dtype('int64')

In [ ]:
C = np.array([1.2, 6.7])

In [ ]:
C.astype(int)

array([1, 6])

In [ ]:
int(7.8)

7

In [ ]:
C.astype(float)

array([[ -2.,  -2.,   3.,  10.,  15.],
       [  2., -20.,   3.,   8.,  15.]])

In [ ]:
(C / 4).astype(int)

array([[ 0,  0,  1,  2,  3],
       [ 0, -5,  0,  2,  3]])

In [ ]:
C = np.array([[-2, -2, 3, 10, 15], [2, -20, 3, 8, 15]])

In [ ]:
C

array([[ -2,  -2,   3,  10,  15],
       [  2, -20,   3,   8,  15]])

In [ ]:
C.T # транспонирование

array([[ -2,   2],
       [ -2, -20],
       [  3,   3],
       [ 10,   8],
       [ 15,  15]])

In [ ]:
C = np.array([[1, 5], [2, 5]])

In [ ]:
C.min(axis=0)

array([ -2, -20,   3,   8,  15])

In [ ]:
C.min(axis=1)

array([ -2, -20])

In [ ]:
C

array([[ -2,  -2,   3,  10,  15],
       [  2, -20,   3,   8,  15]])

In [ ]:
np.argmax(C, axis=1)

array([4, 4])

In [ ]:
np.median([1, 5, 24, 1 , 7]), np.mean([1, 5, 24, 1 , 7]), np.quantile([1, 5, 24, 1 , 7], 0.5)

(5.0, 7.6, 5.0)

In [ ]:
A = np.array([[1, 2, 3], [2, 1, 0], [2, 1, 2]])
B = np.array([[-3, 8, 0.7], [1, 1, 1], [-1, 9, 12]])
print('A\n', A)
print('B\n', B)
print('A^T\n', A.transpose()) # транспонирование
print('A * B\n', A.dot(B), '\nB * A\n', B.dot(A)) # умножение матриц
print('|A|: ', np.linalg.det(A))
print('A^10:\n', np.linalg.matrix_power(A, 10))

A
 [[1 2 3]
 [2 1 0]
 [2 1 2]]
B
 [[-3.   8.   0.7]
 [ 1.   1.   1. ]
 [-1.   9.  12. ]]
A^T
 [[1 2 2]
 [2 1 1]
 [3 0 2]]
A * B
 [[-4.  37.  38.7]
 [-5.  17.   2.4]
 [-7.  35.  26.4]] 
B * A
 [[14.4  2.7 -7.6]
 [ 5.   4.   5. ]
 [41.  19.  21. ]]
|A|:  -6.0
A^10:
 [[2601131 2116219 2803749]
 [1375060 1118813 1482318]
 [2363272 1922795 2547502]]


### Pandas

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
data1 = pd.Series(array1, index=['a', 'b', 'c', 'd', 'e'])

In [ ]:
data1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
data2 = pd.DataFrame([array1], columns=['a', 'b', 'c', 'd', 'e'])
data2

a  b  c  d  e
0  1  2  3  4  5

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/arl20/python_2024_AI/refs/heads/main/datasets/flats.csv')

In [ ]:
df.head(3)

Price Apartment type Metro station  Minutes to metro         Region  \
0  6,300,000.00      Secondary       Опалиха              6.00  Moscow region   
1  9,000,000.00      Secondary       Павшино              2.00  Moscow region   
2 11,090,000.00      Secondary      Мякинино             14.00  Moscow region   

   Number of rooms  Area  Living area  Kitchen area  Floor  Number of floors  \
0             1.00 30.60        11.10          8.50  25.00                25   
1             1.00 49.20        20.00         10.00   6.00                15   
2             1.00 44.70        16.20         13.10  10.00                25   

                  Renovation  
0                   Cosmetic  
1  European-style renovation  
2                   Cosmetic

In [ ]:
df.shape

(22676, 12)

In [ ]:
df.head() # первые 5 строк

Price Apartment type Metro station  Minutes to metro         Region  \
0   6300000.0      Secondary       Опалиха               6.0  Moscow region   
1   9000000.0      Secondary       Павшино               2.0  Moscow region   
2  11090000.0      Secondary      Мякинино              14.0  Moscow region   
3   8300000.0      Secondary      Строгино               8.0  Moscow region   
4   6450000.0      Secondary       Опалиха               6.0  Moscow region   

   Number of rooms  Area  Living area  Kitchen area  Floor  Number of floors  \
0              1.0  30.6         11.1           8.5   25.0                25   
1              1.0  49.2         20.0          10.0    6.0                15   
2              1.0  44.7         16.2          13.1   10.0                25   
3              1.0  35.1         16.0          11.0   12.0                33   
4              1.0  37.7         15.2           4.0    5.0                 5   

                  Renovation  
0                   Cosmetic  
1  European-style renovation  
2                   Cosmetic  
3  European-style renovation  
4         Without renovation

In [ ]:
df.tail()

Price Apartment type  Metro station  Minutes to metro  \
22671 4,768,792.00   New building     Котельники              8.00   
22672 5,900,000.00   New building  Домодедовская             25.00   
22673 3,700,000.00   New building     Котельники             30.00   
22674 5,768,869.00   New building       Жулебино             14.00   
22675 6,839,157.00   New building     Котельники              8.00   

              Region  Number of rooms  Area  Living area  Kitchen area  Floor  \
22671  Moscow region             0.00 31.75        13.00          5.00   4.00   
22672  Moscow region             1.00 31.60        10.10         12.20  11.00   
22673  Moscow region             0.00 18.00        15.00          8.10  17.00   
22674  Moscow region             2.00 36.39        22.00          6.60  12.00   
22675  Moscow region             2.00 56.13        32.00          5.00  10.00   

       Number of floors Renovation  
22671                17   Cosmetic  
22672                15   Cosmetic  
22673                17   Cosmetic  
22674                14   Cosmetic  
22675                17   Cosmetic

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22676 entries, 0 to 22675
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Price             22676 non-null  float64
 1   Apartment type    22676 non-null  object 
 2   Metro station     22676 non-null  object 
 3   Minutes to metro  22676 non-null  float64
 4   Region            22676 non-null  object 
 5   Number of rooms   22676 non-null  float64
 6   Area              22676 non-null  float64
 7   Living area       22676 non-null  float64
 8   Kitchen area      22676 non-null  float64
 9   Floor             22676 non-null  float64
 10  Number of floors  22676 non-null  int64  
 11  Renovation        22676 non-null  object 
dtypes: float64(7), int64(1), object(4)
memory usage: 2.1+ MB


In [ ]:
df.describe()

Price  Minutes to metro  Number of rooms      Area  \
count        22,676.00         22,676.00        22,676.00 22,676.00   
mean     36,121,321.82             11.89             2.04     71.97   
std      82,825,614.18              6.20             1.52     68.37   
min       1,150,000.00              0.00             0.00      6.00   
25%       7,068,116.00              7.00             1.00     37.40   
50%      11,343,200.00             11.00             2.00     53.30   
75%      24,799,247.50             15.00             3.00     77.14   
max   2,455,020,000.00             60.00            12.00  1,117.00   

       Living area  Kitchen area     Floor  Number of floors  
count    22,676.00     22,676.00 22,676.00         22,676.00  
mean         38.52         12.59      9.19             16.56  
std          38.12          7.73      7.55              9.78  
min           2.00          1.00      1.00              1.00  
25%          17.60          8.60      4.00             11.00  
50%          28.50         10.60      8.00             16.00  
75%          43.20         14.50     13.00             20.00  
max         566.80        122.00     92.00             97.00

In [ ]:
df.describe(include = 'object')

Apartment type      Metro station  Region Renovation
count           22676              22676   22676      22676
unique              2                547       2          4
top         Secondary  Красногвардейская  Moscow   Cosmetic
freq            13152               2697   16113      12788

In [ ]:
pd.options.display.float_format = '{:,.2f}'.format

In [ ]:
df.head()

Price Apartment type Metro station  Minutes to metro         Region  \
0  6,300,000.00      Secondary       Опалиха              6.00  Moscow region   
1  9,000,000.00      Secondary       Павшино              2.00  Moscow region   
2 11,090,000.00      Secondary      Мякинино             14.00  Moscow region   
3  8,300,000.00      Secondary      Строгино              8.00  Moscow region   
4  6,450,000.00      Secondary       Опалиха              6.00  Moscow region   

   Number of rooms  Area  Living area  Kitchen area  Floor  Number of floors  \
0             1.00 30.60        11.10          8.50  25.00                25   
1             1.00 49.20        20.00         10.00   6.00                15   
2             1.00 44.70        16.20         13.10  10.00                25   
3             1.00 35.10        16.00         11.00  12.00                33   
4             1.00 37.70        15.20          4.00   5.00                 5   

                  Renovation  
0                   Cosmetic  
1  European-style renovation  
2                   Cosmetic  
3  European-style renovation  
4         Without renovation

In [ ]:
df['Price']

0        6,300,000.00
1        9,000,000.00
2       11,090,000.00
3        8,300,000.00
4        6,450,000.00
             ...     
22671    4,768,792.00
22672    5,900,000.00
22673    3,700,000.00
22674    5,768,869.00
22675    6,839,157.00
Name: Price, Length: 22676, dtype: float64

In [ ]:
df['Price'].mean(), df.Price.median()

(36121321.81531134, 11343200.0)

In [ ]:
df[['Price', 'Metro station']].head(1)

Price Metro station
0 6,300,000.00       Опалиха

In [ ]:
print(df['Region'].unique())
df['Region'].unique()

['Moscow region' 'Moscow']


array(['Moscow region', 'Moscow'], dtype=object)

In [ ]:
df.head()

Price Apartment type Metro station  Minutes to metro         Region  \
0  6,300,000.00      Secondary       Опалиха              6.00  Moscow region   
1  9,000,000.00      Secondary       Павшино              2.00  Moscow region   
2 11,090,000.00      Secondary      Мякинино             14.00  Moscow region   
3  8,300,000.00      Secondary      Строгино              8.00  Moscow region   
4  6,450,000.00      Secondary       Опалиха              6.00  Moscow region   

   Number of rooms  Area  Living area  Kitchen area  Floor  Number of floors  \
0             1.00 30.60        11.10          8.50  25.00                25   
1             1.00 49.20        20.00         10.00   6.00                15   
2             1.00 44.70        16.20         13.10  10.00                25   
3             1.00 35.10        16.00         11.00  12.00                33   
4             1.00 37.70        15.20          4.00   5.00                 5   

                  Renovation  
0                   Cosmetic  
1  European-style renovation  
2                   Cosmetic  
3  European-style renovation  
4         Without renovation

In [ ]:
df.columns

Index(['Price', 'Apartment type', 'Metro station', 'Minutes to metro',
       'Region', 'Number of rooms', 'Area', 'Living area', 'Kitchen area',
       'Floor', 'Number of floors', 'Renovation'],
      dtype='object')

In [ ]:
df.index = df.index + 1

In [ ]:
df.head()

Price Apartment type Metro station  Minutes to metro         Region  \
1  6,300,000.00      Secondary       Опалиха              6.00  Moscow region   
2  9,000,000.00      Secondary       Павшино              2.00  Moscow region   
3 11,090,000.00      Secondary      Мякинино             14.00  Moscow region   
4  8,300,000.00      Secondary      Строгино              8.00  Moscow region   
5  6,450,000.00      Secondary       Опалиха              6.00  Moscow region   

   Number of rooms  Area  Living area  Kitchen area  Floor  Number of floors  \
1             1.00 30.60        11.10          8.50  25.00                25   
2             1.00 49.20        20.00         10.00   6.00                15   
3             1.00 44.70        16.20         13.10  10.00                25   
4             1.00 35.10        16.00         11.00  12.00                33   
5             1.00 37.70        15.20          4.00   5.00                 5   

                  Renovation  
1                   Cosmetic  
2  European-style renovation  
3                   Cosmetic  
4  European-style renovation  
5         Without renovation

In [ ]:
df.loc[0]

KeyError: 0

In [ ]:
df.iloc[0]

Price                6,300,000.00
Apartment type          Secondary
Metro station             Опалиха
Minutes to metro             6.00
Region              Moscow region
Number of rooms              1.00
Area                        30.60
Living area                 11.10
Kitchen area                 8.50
Floor                       25.00
Number of floors               25
Renovation               Cosmetic
Name: 1, dtype: object

### Фильтрация и сортировка

In [ ]:
df[['Price']]

Price
1      6,300,000.00
2      9,000,000.00
3     11,090,000.00
4      8,300,000.00
5      6,450,000.00
...             ...
22672  4,768,792.00
22673  5,900,000.00
22674  3,700,000.00
22675  5,768,869.00
22676  6,839,157.00

[22676 rows x 1 columns]

In [ ]:
df[df['Region'] == 'Moscow'][['Price', 'Number of rooms']].mean() # среднее число комнат и цена квартир в Москве

Price             47,983,477.58
Number of rooms            2.22
dtype: float64

In [ ]:
df[df['Region'] != 'Moscow'][['Price', 'Number of rooms']].mean() # и не в Москве

Price             6,998,220.22
Number of rooms           1.60
dtype: float64

In [ ]:
df[(df['Region'] == 'Moscow') & (df['Apartment type'] == 'Secondary')][['Price', 'Number of rooms']].mean() # средняя цена вторички в Москве

Price             58,738,445.12
Number of rooms            2.38
dtype: float64

In [ ]:
df.shape

(22676, 12)

In [ ]:
df.columns

Index(['Price', 'Apartment type', 'Metro station', 'Minutes to metro',
       'Region', 'Number of rooms', 'Area', 'Living area', 'Kitchen area',
       'Floor', 'Number of floors', 'Renovation'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=1, stop=22677, step=1)

In [ ]:
df.select_dtypes(['int', 'float'])

Price  Minutes to metro  Number of rooms  Area  Living area  \
1      6,300,000.00              6.00             1.00 30.60        11.10   
2      9,000,000.00              2.00             1.00 49.20        20.00   
3     11,090,000.00             14.00             1.00 44.70        16.20   
4      8,300,000.00              8.00             1.00 35.10        16.00   
5      6,450,000.00              6.00             1.00 37.70        15.20   
...             ...               ...              ...   ...          ...   
22672  4,768,792.00              8.00             0.00 31.75        13.00   
22673  5,900,000.00             25.00             1.00 31.60        10.10   
22674  3,700,000.00             30.00             0.00 18.00        15.00   
22675  5,768,869.00             14.00             2.00 36.39        22.00   
22676  6,839,157.00              8.00             2.00 56.13        32.00   

       Kitchen area  Floor  Number of floors  
1              8.50  25.00                25  
2             10.00   6.00                15  
3             13.10  10.00                25  
4             11.00  12.00                33  
5              4.00   5.00                 5  
...             ...    ...               ...  
22672          5.00   4.00                17  
22673         12.20  11.00                15  
22674          8.10  17.00                17  
22675          6.60  12.00                14  
22676          5.00  10.00                17  

[22676 rows x 8 columns]

In [ ]:
df.sort_values(by = 'Price').head()

Price Apartment type  Metro station  Minutes to metro  \
13028 1,150,000.00      Secondary     Покровское             32.00   
12990 1,420,000.00      Secondary      Кузьминки             18.00   
12864 1,560,000.00      Secondary      Кузьминки             18.00   
12808 1,750,000.00      Secondary    Университет             14.00   
18008 1,939,125.00   New building  Алма-Атинская             13.00   

              Region  Number of rooms  Area  Living area  Kitchen area  Floor  \
13028         Moscow             0.00  6.00         5.20          7.10   2.00   
12990         Moscow             0.00 15.20        11.00          7.90   1.00   
12864         Moscow             0.00 12.00         9.00          7.60   1.00   
12808         Moscow             0.00 14.80        12.00          7.90   1.00   
18008  Moscow region             0.00 16.97        10.70          8.00  12.00   

       Number of floors          Renovation  
13028                18  Without renovation  
12990                 5  Without renovation  
12864                 5  Without renovation  
12808                 9            Cosmetic  
18008                16            Cosmetic

In [ ]:
df.sort_values(by='Price', ascending=False).head()

Price Apartment type       Metro station  Minutes to metro  \
4091  2,455,020,000.00      Secondary          Маяковская              1.00   
12841 1,732,170,825.00      Secondary         Охотный ряд              7.00   
9805  1,517,997,000.00      Secondary       Парк культуры              8.00   
3898  1,475,430,000.00      Secondary   Площадь Революции              0.00   
9678  1,422,120,000.00      Secondary          Боровицкая             14.00   

       Region  Number of rooms     Area  Living area  Kitchen area  Floor  \
4091   Moscow             6.00 1,067.40       541.80         95.00   9.00   
12841  Moscow             0.00   719.00       300.00         50.00   5.00   
9805   Moscow             6.00   584.10       297.40         55.00   5.00   
3898   Moscow             5.00   657.50       334.50         61.00   1.00   
9678   Moscow             5.00   508.00       225.00         25.00   4.00   

       Number of floors          Renovation  
4091                  9            Designer  
12841                 5  Without renovation  
9805                  5            Designer  
3898                  5            Designer  
9678                  4  Without renovation

In [ ]:
df.sort_values(by=['Price', 'Number of rooms'], ascending=[True, False]).head()

Price Apartment type  Metro station  Minutes to metro  \
13028 1,150,000.00      Secondary     Покровское             32.00   
12990 1,420,000.00      Secondary      Кузьминки             18.00   
12864 1,560,000.00      Secondary      Кузьминки             18.00   
12808 1,750,000.00      Secondary    Университет             14.00   
17952 1,939,125.00   New building  Алма-Атинская             13.00   

              Region  Number of rooms  Area  Living area  Kitchen area  Floor  \
13028         Moscow             0.00  6.00         5.20          7.10   2.00   
12990         Moscow             0.00 15.20        11.00          7.90   1.00   
12864         Moscow             0.00 12.00         9.00          7.60   1.00   
12808         Moscow             0.00 14.80        12.00          7.90   1.00   
17952  Moscow region             0.00 16.97        10.70          8.00  14.00   

       Number of floors          Renovation  
13028                18  Without renovation  
12990                 5  Without renovation  
12864                 5  Without renovation  
12808                 9            Cosmetic  
17952                16            Cosmetic

In [ ]:
for col in df.select_dtypes(['object']).columns:
  print(f'{col}: {df[col].unique()[:10]}')

Apartment type: ['Secondary' 'New building']
Metro station: [' Опалиха' ' Павшино' ' Мякинино' ' Строгино' ' Нахабино'
 ' Красногорская' ' Тушинская' ' Аникеевка' ' Волоколамская' ' Пенягино']
Region: ['Moscow region' 'Moscow']
Renovation: ['Cosmetic' 'European-style renovation' 'Without renovation' 'Designer']


In [ ]:
df.columns

Index(['Price', 'Apartment type', 'Metro station', 'Minutes to metro',
       'Region', 'Number of rooms', 'Area', 'Living area', 'Kitchen area',
       'Floor', 'Number of floors', 'Renovation'],
      dtype='object')

In [ ]:
df.head(1)

Price Apartment type Metro station  Minutes to metro         Region  \
1 6,300,000.00      Secondary       Опалиха              6.00  Moscow region   

   Number of rooms  Area  Living area  Kitchen area  Floor  Number of floors  \
1             1.00 30.60        11.10          8.50  25.00                25   

  Renovation  
1   Cosmetic

In [ ]:
df['Renovation'].unique()

array(['Cosmetic', 'European-style renovation', 'Without renovation',
       'Designer'], dtype=object)

**Задание 1**. Чему равна средняя цена квартир в Москве с косметическим ремонтом или без ремонта?

In [ ]:
df[(df['Region'] == 'Moscow') & (df['Renovation'].isin(['Cosmetic', 'Without renovation']))]['Price'].mean()

31246510.59684123

**Задание 2**. Какое среднее число комнат у квартир в Московской области, которые дороже 3 млн рублей?


**Задание 3** Насколько отличается площадь кухни в новостройках и вторичке?