<a href="https://colab.research.google.com/github/TaniaZharova2205/HSE/blob/main/Seminar_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Рекурсия

In [ ]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)
print(factorial(5))

120


In [ ]:
!n = (n-1)! * n

In [ ]:
print(factorial(3))

6


In [ ]:
print(factorial(6150))

RecursionError: maximum recursion depth exceeded in comparison

In [ ]:
import sys

In [ ]:
sys.getrecursionlimit()

1100

In [ ]:
sys.setrecursionlimit(1200)

In [ ]:
sys.getrecursionlimit()

1200

### Декораторы


Функция, которая принимает другую функцию и изменяет её функциональность без изменения её кода.

In [ ]:
def uppercase(func):  # передаем функцию, которую будем оборачивать
    def wrapper():
        result = func()
        return result.upper()
    return wrapper # вернуть нужно функцию-обертку

@uppercase
def print_hello(st=''):
    return "hello world" + st

In [ ]:
print_hello()

'HELLO WORLD'

### Задание 1

Напишите декоратор repeat_twice, который будет выполнять функцию 2 раза. Функция не принимает аргументов и ничего не возращает, только печатает что-то на экран.

In [2]:
def repeat_twice(func):
    def wrapper():
        func()
        func()
    return wrapper

In [3]:
def repeat_3(func):
    def wrapper():
        func()
        func()
        func()
    return wrapper

In [4]:
@repeat_twice
@repeat_3
def print_hello(st=''):
    print("hello world")

In [5]:
print_hello()

hello world
hello world
hello world
hello world
hello world
hello world


### Задание 2

Напишите декоратор, который считает время работы функции

In [ ]:
import time

In [ ]:
start = time.time()

In [ ]:
end = time.time()

In [ ]:
print(end - start)

4.780577898025513


In [ ]:
def time_decorator(func):
  def wrapper():
    start = time.time()
    result = func()
    end = time.time()
    print(end - start)
    return result
  return wrapper

In [ ]:
@time_decorator
def print_hello(st=''):
    return "hello world"

In [ ]:
def simple_decorator(func):
  return func() * 2

In [ ]:
@simple_decorator
def print_hello(st=''):
    return "hello world"

In [ ]:
result = print_hello()

TypeError: 'str' object is not callable

In [ ]:
result

'hello world'

### Еще задача из контеста

Создайте декоратор log_plagiat_check, который будет использоваться для функции is_plagiat из предыдущей задачи. Этот декоратор должен выводить на экран информацию о том, какие слова проверяются и какой результат проверки.

Решение обязательно должно содержать:

* код декоратора log_plagiat_check
* код функции is_plagiat
* чтение входных данных и применение функции is_plagiat

Входные данные необходимо считать из файла "words.txt". Файл содержит неизвестное число строк. Каждая строка содержит два слова через пробел. Необходимо для каждой строки вывести на экран:

* оба слова
* результат действия функции is_plagiat


**Формат ввода**

Файл words.txt.

Файл содержит неизвестное число строк. Каждая строка содержит два слова через пробел.

**Формат вывода**


Строка формата "Check '{слово1}' vs '{слово2}' -> {True/False}"

Библиотека NumPy (Numeric Python)  —  быстрая библиотека для математики в Python. Основная структура данных  —  массив `numpy.array` для хранения данных одного типа

##### Создание массива

In [ ]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([0.01, 2, 4, 0.1, -2, 0, 1, -2])

print(a)
print(b)
print(b[1])
print(b[1:7:2])

[1 2 3 4 5]
[ 0.01  2.    4.    0.1  -2.    0.    1.   -2.  ]
2.0
[2.  0.1 0. ]


In [ ]:
lst = [1, 2, ['a', 'b']]

In [ ]:
c = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [10, 20, 30, -10, 0]]) # многомерный массив
print(c)
print(c.shape, c.dtype)
print( c[1][2])

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 10  20  30 -10   0]]
(3, 5) int64
8


In [ ]:
d = np.arange(2, 19, 3)
print(d)

[ 2  5  8 11 14 17]


In [ ]:
print(np.random.rand(2, 2)) # массив из чисел их равномерного распределения [0, 1]

[[0.7425805  0.82818143]
 [0.4561039  0.16767254]]


In [ ]:
random_array = np.random.randn(2, 3, 2)
random_array


array([[[ 2.89249971, -0.78046019],
        [-0.64531817, -0.38237243],
        [-0.85085918, -1.83803109]],

       [[ 0.01772884,  1.30015334],
        [ 1.2180914 , -0.56668047],
        [-0.51167483,  0.31392278]]])

In [ ]:
random_array.shape

(2, 3, 2)

Используются типы данных Си: `int8`, `int32`, `int64`...

In [ ]:
c[1][2] = 80

In [ ]:
c

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 10,  20,  30, -10,   0]])

In [ ]:
c[1][2] = 80

In [ ]:
c.dtype

dtype('int64')

In [ ]:
c[1][2] = 10e18 #переполнение

OverflowError: Python int too large to convert to C long

In [ ]:
10e18

1e+19

In [ ]:
I = np.eye(10, 10)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
array = np.array([0, 1, 2, 3, 4, 5])
print(array.dtype)
array

int64


array([0, 1, 2, 3, 4, 5])

In [ ]:
array = np.array([0, 1, 2, 3, 4, 5], dtype='int16')
print(array.dtype)
array

int16


array([0, 1, 2, 3, 4, 5], dtype=int16)

In [ ]:
array[1] =array[1] * 10

In [ ]:
array[1] = 'abc'

ValueError: invalid literal for int() with base 10: 'abc'

In [ ]:
array = np.array([0, 1, 'abc'])
print(array.dtype)
array

<U21


array(['0', '1', 'abc'], dtype='<U21')

In [ ]:
array = np.array(['abc', 'def'])
print(array.dtype)
array

<U3


array(['abc', 'def'], dtype='<U3')

In [ ]:
a = np.zeros(10)
print(a)

a = np.zeros((3, 2))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


Многомерные массивы:

In [ ]:
array = np.array([[[1, 10], [2, 12], [3, 30]], [[4, 40], [5, 50], [6, 60]], [[7, 70], [8, 80], [9, 90]]])

In [ ]:
print(array)

[[[ 1 10]
  [ 2 12]
  [ 3 30]]

 [[ 4 40]
  [ 5 50]
  [ 6 60]]

 [[ 7 70]
  [ 8 80]
  [ 9 90]]]


In [ ]:
print(array.dtype, array.shape, array.ndim, array.size)

int64 (3, 3, 2) 3 18


In [ ]:
array.flatten()

array([ 1, 10,  2, 12,  3, 30,  4, 40,  5, 50,  6, 60,  7, 70,  8, 80,  9,
       90])

In [ ]:
array.reshape(3, 5)

ValueError: cannot reshape array of size 18 into shape (3,5)

In [ ]:
array.reshape(2, 9)

array([[ 1, 10,  2, 12,  3, 30,  4, 40,  5],
       [50,  6, 60,  7, 70,  8, 80,  9, 90]])

In [ ]:
np.array([[0, 0.1, 1],
         [0, 1, 2]])

array([[0. , 0.1, 1. ],
       [0. , 1. , 2. ]])

In [ ]:
array = np.array([[1, 2], [1, 2, 3]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
array = np.array([[1, 2], [1, 2, 3]], dtype="object")

In [ ]:
print(array, array.dtype)

[list([1, 2]) list([1, 2, 3])] object


In [ ]:
array.flatten()

array([list([1, 2]), list([1, 2, 3])], dtype=object)

С numpy-массивами может быть удобно работать, потому что все действия в них выполняются поэлементно:

In [ ]:
lst1 = [0, 1, 2, 3, 4, 5]
lst2 = [3, 1, 28, 3, 2, 8]
print(lst1 + lst2)

[0, 1, 2, 3, 4, 5, 3, 1, 28, 3, 2, 8]


In [ ]:
array1 = np.array([0, 1, 2, 3, 4, 5])
array2 = np.array([3, 1, 28, 3, 2, 8])
print(array1 + array2)

[ 3  2 30  6  6 13]


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[-2, 3, 8], [1, 9, 11]])
print(A, end = '\n\n')
print(B, end = '\n\n')
print(A + B, end = '\n\n')
print(A * B, end = '\n\n') # не умножение матриц, а поэлементное умножение!
print(np.dot(A, B)) # а вот это умножение матриц, которое упадет из-за несоответствия размерностей

[[1 2 3]
 [4 5 6]]

[[-2  3  8]
 [ 1  9 11]]

[[-1  5 11]
 [ 5 14 17]]

[[-2  6 24]
 [ 4 45 66]]



ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
C = np.array([[1, 2], [4, 5], [6, 7]])
print(B)
print(C)
print(np.dot(B, C))

[[-2  3  8]
 [ 1  9 11]]
[[1 2]
 [4 5]
 [6 7]]
[[ 58  67]
 [103 124]]


In [ ]:
print(C / 4) # деление на число

[[0.25 0.5 ]
 [1.   1.25]
 [1.5  1.75]]


##### Арифметические операции

In [ ]:
lst1 = [1, 2, 3]
lst2 = [-1, -6, 30]
print(lst1 + lst2)

lst1_array = np.array([1, 2, 3])
lst2_array = np.array([-1, -6, 30])
print(lst1_array + lst2_array)

[1, 2, 3, -1, -6, 30]
[ 0 -4 33]


Если в операции участвуют два массива одинакового размера, операции считаются для соответствующих пар:

In [ ]:
print(lst2_array)
print(lst2_array * 6)
print(lst2_array * 2.8)
print(lst2_array + 2)
print(lst2_array - 20)
print(lst2_array**2)

[-1 -6 30]
[ -6 -36 180]
[ -2.8 -16.8  84. ]
[ 1 -4 32]
[-21 -26  10]
[  1  36 900]


In [ ]:
print(lst1_array)
print(lst2_array)
print()
print(lst1_array * lst2_array)
print(lst1_array - lst2_array)
print(lst1_array / lst2_array)
print(lst1_array // lst2_array)
print(lst1_array ** 2)

In [ ]:
np.unique([1, 2, 4, 2, 2, 1]) # уникальные значения

In [ ]:
print(C.dtype, C.shape, C.ndim, C.size)

int64 (3, 2) 2 6


##### Индексация

In [ ]:
a = np.array([1, -2, 25, -4, -12])
print(a[a > 0])

[ 1 25]


In [ ]:
a = np.array([ 1,  2, 25, 10, -1])

In [ ]:
b = np.array([-2, -2,  3, 10, 15, 3])

In [ ]:
print(a[(a > 0) | (b > 0)])

ValueError: operands could not be broadcast together with shapes (5,) (6,) 

In [ ]:
print(a[(a > 0) & (b > 0)])

[25 10]


In [ ]:
C = np.array([[-2, -2, 3, 10, 15], [2, -2, 3, 8, 15]])

In [ ]:
import numpy as np
a = np.random.randn(10,20,30)
print(a[:,:,:2].shape)
print(a[:,:, [0,1]].shape)
print(a[0,:,:2].shape)
print(a[0,:, [0,1]].shape)

(10, 20, 2)
(10, 20, 2)
(20, 2)
(2, 20)


In [ ]:
a = np.array([[[1, 2], [3, 4], [5, 6]]])

In [ ]:
a.shape

(1, 3, 2)

In [ ]:
a

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [ ]:
a[0][[0, 1]]

array([[1, 2],
       [3, 4]])

In [ ]:
a[0][:2]

array([[1, 2],
       [3, 4]])

In [ ]:
min(C[0])

-2

In [ ]:
np.min(C, axis=0)

array([-2, -2,  3,  8, 15])

In [ ]:
import numpy as np


In [ ]:
C[0][2] = 7

In [ ]:
C

array([[-2, -2,  7, 10, 15],
       [ 2, -2,  3,  8, 15]])

##### Математика

In [ ]:
a = np.array([1, 2, 25, 10, -1])
np.mean(a), np.min(a), np.max(a), np.sum(a), np.std(a)

(7.4, -1, 25, 37, 9.562426470305537)

In [ ]:
print(np.sin(2), np.exp(2))
print(np.sin(a), np.exp(a))

0.9092974268256817 7.38905609893065
[ 0.84147098  0.90929743 -0.13235175 -0.54402111 -0.84147098] [2.71828183e+00 7.38905610e+00 7.20048993e+10 2.20264658e+04
 3.67879441e-01]


In [ ]:
C.astype(float)

array([[1., 2.],
       [4., 5.],
       [6., 7.]])

In [ ]:
(C / 4).astype(int)

array([[0, 0],
       [1, 1],
       [1, 1]])

In [ ]:
C.T # транспонирование

array([[1, 4, 6],
       [2, 5, 7]])

In [ ]:
array

array([[[ 1, 10],
        [ 2, 12],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]]])

In [ ]:
C = np.array([[1, 5], [2, 5]])

In [ ]:
C.min(axis=0)

array([1, 5])

In [ ]:
C.min(axis=1)

array([1, 2])

In [ ]:
array.min(axis=0)

array([[ 1, 10],
       [ 2, 12],
       [ 3, 30]])

In [ ]:
array.min(axis=1)

array([[ 1, 10],
       [ 4, 40],
       [ 7, 70]])

In [ ]:
array.min(axis=2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.min(array, axis=1)

array([[ 1, 10],
       [ 4, 40],
       [ 7, 70]])

In [ ]:
np.argmax(array, axis=1)

array([[2, 2],
       [2, 2],
       [2, 2]])

In [ ]:
np.median([1, 5, 24, 1 , 7]), np.mean([1, 5, 24, 1 , 7]), np.quantile([1, 5, 24, 1 , 7], 0.5)

(5.0, 7.6, 5.0)

In [ ]:
array.cumsum()

array([  1,  11,  13,  25,  28,  58,  62, 102, 107, 157, 163, 223, 230,
       300, 308, 388, 397, 487])

In [ ]:
A = np.array([[1, 2, 3], [2, 1, 0], [2, 1, 2]])
B = np.array([[-3, 8, 0.7], [1, 1, 1], [-1, 9, 12]])
print('A\n', A)
print('B\n', B)
print('A^T\n', A.transpose()) # транспонирование
print('A * B\n', A.dot(B), '\nB * A\n', B.dot(A)) # умножение матриц
print('|A|: ', np.linalg.det(A))
print('A^10:\n', np.linalg.matrix_power(A, 10))

A
 [[1 2 3]
 [2 1 0]
 [2 1 2]]
B
 [[-3.   8.   0.7]
 [ 1.   1.   1. ]
 [-1.   9.  12. ]]
A^T
 [[1 2 2]
 [2 1 1]
 [3 0 2]]
A * B
 [[-4.  37.  38.7]
 [-5.  17.   2.4]
 [-7.  35.  26.4]] 
B * A
 [[14.4  2.7 -7.6]
 [ 5.   4.   5. ]
 [41.  19.  21. ]]
|A|:  -6.0
A^10:
 [[2601131 2116219 2803749]
 [1375060 1118813 1482318]
 [2363272 1922795 2547502]]


### Pandas

In [ ]:
import pandas as pd

In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
data1 = pd.Series(array1, index=['a', 'b', 'c', 'd', 'e'])

In [ ]:
data1

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
data2 = pd.DataFrame(array1, index=['a', 'b', 'c', 'd', 'e'])
data2

0
a  1
b  2
c  3
d  4
e  5

In [ ]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       5 non-null      int64
dtypes: int64(1)
memory usage: 80.0+ bytes


In [ ]:
data3 = pd.DataFrame([array1], columns=['a', 'b', 'c', 'd', 'e'])
data3

a  b  c  d  e
0  1  2  3  4  5

In [ ]:
data = [1, 2, 3, 4]
s = pd.Series(data, index=['a', 'b', 'c', 'd'])

In [ ]:
data = {
    'row1': [1, 'a', 3.5],
    'row2': [2, 'b', 4.5],
    'row3': [3, 'c', 5.5]
}
df = pd.DataFrame.from_dict(data, orient='index', columns=['Number', 'Letter', 'Float'])

print(df)

      Number Letter  Float
row1       1      a    3.5
row2       2      b    4.5
row3       3      c    5.5


In [ ]:
df.shape

(3, 3)

In [ ]:
df.index

Index(['row1', 'row2', 'row3'], dtype='object')

In [ ]:
df.columns

Index(['Number', 'Letter', 'Float'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, row1 to row3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Number  3 non-null      int64  
 1   Letter  3 non-null      object 
 2   Float   3 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 96.0+ bytes


In [ ]:
df.dtypes

Number      int64
Letter     object
Float     float64
dtype: object

In [ ]:
df.select_dtypes([int])

Number
row1       1
row2       2
row3       3

In [ ]:
df

Number Letter  Float
row1       1      a    3.5
row2       2      b    4.5
row3       3      c    5.5

In [ ]:
df[df['Number'] > 1]

Number Letter  Float
row2       2      b    4.5
row3       3      c    5.5

In [ ]:
df.describe()

Number  Float
count     3.0    3.0
mean      2.0    4.5
std       1.0    1.0
min       1.0    3.5
25%       1.5    4.0
50%       2.0    4.5
75%       2.5    5.0
max       3.0    5.5

In [ ]:
df.describe(include='object')

Letter
count       3
unique      3
top         a
freq        1

In [ ]:
df.min()

Number      1
Letter      a
Float     3.5
dtype: object

In [ ]:
df

Number Letter  Float
row1       1      a    3.5
row2       2      b    4.5
row3       3      c    5.5

In [ ]:
df.min(axis=0)

Number      1
Letter      a
Float     3.5
dtype: object

In [ ]:
df[['Number', 'Float']].min(axis=1)

row1    1.0
row2    2.0
row3    3.0
dtype: float64

In [ ]:
df[['Number', 'Float']].min(axis=1)

row1    1.0
row2    2.0
row3    3.0
dtype: float64

In [ ]:
df[['Number', 'Float']].max(axis=1)

row1    3.5
row2    4.5
row3    5.5
dtype: float64

In [ ]:
df.iloc[0]

Number      1
Letter      a
Float     3.5
Name: row1, dtype: object

In [ ]:
df.loc['row1']

Number      1
Letter      a
Float     3.5
Name: row1, dtype: object

In [ ]:
df.describe()

Number  Float
count     3.0    3.0
mean      2.0    4.5
std       1.0    1.0
min       1.0    3.5
25%       1.5    4.0
50%       2.0    4.5
75%       2.5    5.0
max       3.0    5.5

In [ ]:
df.describe(include).T

count unique  top freq mean  std  min  25%  50%  75%  max
Number   3.0    NaN  NaN  NaN  2.0  1.0  1.0  1.5  2.0  2.5  3.0
Letter     3      3    a    1  NaN  NaN  NaN  NaN  NaN  NaN  NaN
Float    3.0    NaN  NaN  NaN  4.5  1.0  3.5  4.0  4.5  5.0  5.5

In [ ]:
data = {
    'row1': [1, 'a', 3.5],
    'row2': [2, 'b', 4.5],
    'row3': [3, 'c', 5.5],
    'row4': [4, 'c', 7.5],
    'row5': [4, 'b', 7.5]
}
df = pd.DataFrame.from_dict(data, orient='index', columns=['Number', 'Letter', 'Float'])

print(df)

      Number Letter  Float
row1       1      a    3.5
row2       2      b    4.5
row3       3      c    5.5
row4       4      c    7.5
row5       4      b    7.5


In [ ]:
df.groupby(['Letter']).agg({'Float' : 'sum', 'Number' : 'mean'})

Float  Number
Letter               
a         3.5     1.0
b        12.0     3.0
c        13.0     3.5

In [ ]:
df['Number_2'] = df['Number']**2

In [ ]:
df

Number Letter  Float  Number_2
row1       1      a    3.5         1
row2       2      b    4.5         4
row3       3      c    5.5         9
row4       4      c    7.5        16
row5       4      b    7.5        16

In [ ]:
def func(x):
    return int(x > 3)
df['is_high_number'] = df['Number'].apply(func)

In [ ]:
df

Number Letter  Float  Number_2  is_high_number
row1       1      a    3.5         1               0
row2       2      b    4.5         4               0
row3       3      c    5.5         9               0
row4       4      c    7.5        16               1
row5       4      b    7.5        16               1

In [ ]:
df['is_high_number'] = np.where(df['Number'] > 3, 1, 0)

In [ ]:
df

Number Letter  Float  Number_2  is_high_number
row1       1      a    3.5         1               0
row2       2      b    4.5         4               0
row3       3      c    5.5         9               0
row4       4      c    7.5        16               1
row5       4      b    7.5        16               1